name: FuelConsumption
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - streamlit
  - altair
  - pandas
  - numpy
  - scikit-learn
  - pandera
  - ipykernel
  - pip
  - pip:
      - streamlit_extras